### ISSUE TITLE
Remove unnecessary traits and wrapper types from the query crate

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#3884]
### What type of enhancement is this?

Refactor

### What does the enhancement do?

We defined some wrapper types and traits for the query engine
- [x] [Expr](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/common/query/src/logical_plan/expr.rs#L22-L27) https://github.com/GreptimeTeam/greptimedb/pull/3995
- [x] [LogicalPlan](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/query/src/plan.rs#L35-L38) https://github.com/GreptimeTeam/greptimedb/pull/4733
- [x] [LogicalOptimizer](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/query/src/logical_optimizer.rs#L19-L23) #4426
- [x] [PhysicalOptimizer](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/query/src/physical_optimizer.rs#L22-L28) https://github.com/GreptimeTeam/greptimedb/pull/4426
- [x] [PhysicalPlanner](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/query/src/physical_planner.rs#L26-L33) #4412
- [x] [PhysicalPlan](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/common/query/src/physical_plan.rs#L41-L72) https://github.com/GreptimeTeam/greptimedb/pull/3894

Most implementations simply forward requests to datafusion. Since we are highly coupled with datafusion and have no plan to support another query engine, we could remove these types.

### Implementation challenges

For `Expr`:
https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/common/query/src/logical_plan/expr.rs#L22-L27

We could simply remove the `Expr` and re-export datafusion's `Expr`
```rust
pub use datafusion_expr::expr::Expr;
```

The `LogicalPlan` only has one variant so we can replace it with datafusion's `LogicalPlan`. But we also need to refactor [methods](https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/query/src/plan.rs#L41-L90) of the enum so they can take datafusion's `LogicalPlan` as input.
https://github.com/GreptimeTeam/greptimedb/blob/d99746385b8da491d31a953b1d26a348cf00bc73/src/query/src/plan.rs#L35-L38

We could also remove adapters like the [`DfPhysicalPlanAdapter`](https://github.com/GreptimeTeam/greptimedb/blob/main/src/common/query/src/physical_plan.rs#L156-L157) if we remove the `PhysicalPlan`.

Many places use `Expr`, `LogicalPlan`, and `PhysicalPlan`. We might need to refactor them in different PRs.

**Comment by sunheyi6** [comment]
@evenyag i want to pr LogicalPlan part.I took a rough look. Is it to delete the query::plan file and replace all query::plan::LogicalPlan with datafusion_expr::LogicalPlan?

**Comment by evenyag** [comment]
> @evenyag i want to pr LogicalPlan part.I took a rough look. Is it to delete the query::plan file and replace all query::plan::LogicalPlan with datafusion_expr::LogicalPlan?

We can still keep the `query::plan` file as we already implemented some methods for `LogicalPlan`. We may need to implement them as helper functions that take datafusion's plan as a parameter.

**Comment by sunheyi6** [comment]
> > @evenyag i want to pr LogicalPlan part.I took a rough look. Is it to delete the query::plan file and replace all query::plan::LogicalPlan with datafusion_expr::LogicalPlan?
> 
> We can still keep the `query::plan` file as we already implemented some methods for `LogicalPlan`. We may need to implement them as helper functions that take datafusion's plan as a parameter.

Could you please help me check if this modification meets your means?

before:
```rust
    pub fn schema(&self) -> Result<Schema> {
        match self {
            Self::DfPlan(plan) => {
                let df_schema = plan.schema();
                df_schema
                    .clone()
                    .try_into()
                    .context(ConvertDatafusionSchemaSnafu)
            }
        }
    }
```
after:
```rust
    pub fn schema(&self, plan: &DfLogicalPlan) -> Result<Schema> {
        let df_schema = plan.schema();
        df_schema.clone()
            .try_into()
            .context(ConvertDatafusionSchemaSnafu)
    }
```

**Comment by evenyag** [comment]
You should remove `&self`
```rust
fn schema(plan: &DfLogicalPlan) -> Result<Schema> {
    let df_schema = plan.schema();
    df_schema.clone()
        .try_into()
        .context(ConvertDatafusionSchemaSnafu)
}
```

**Comment by sunheyi6** [comment]
I still have some questions.

1. all method shoud remove _pub_ in LogicalPlan?
2. pdate only the plan.rs file or update all files that reference LogicalPlan？

**Comment by leaf-potato** [comment]
@evenyag Remove the remaining 3 traits：
- LogicalOptimizer: https://github.com/GreptimeTeam/greptimedb/pull/4414
- PhysicalOptimizer: https://github.com/GreptimeTeam/greptimedb/pull/4413
- PhysicalPlanner: https://github.com/GreptimeTeam/greptimedb/pull/4412
